project:
  type: website
  output-dir: docs

website:
  title: "Dataframe Optimizer"
  navbar:
    left:
      - text: "Reference"
        href: reference/index.qmd

format:
  html:
    theme: cosmo
    toc: true

quartodoc:
  package: group_32
  dir: reference
  sections:
    - title: Main API
      desc: Main user-facing function.
      contents:
        - group_32.optimize_dataframe.optimize_dataframe

    - title: Column optimizers
      desc: Helpers for optimizing different column types.
      contents:
        - group_32.optimize_numeric.optimize_numeric
        - group_32.optimize_categorical.optimize_categorical
        - group_32.optimize_special.optimize_special
